version: 1

build:
  type: golang  # or "python"
  dockerfile: Dockerfile  # Optional, if not provided, defaults to "Dockerfile"

release:
  rolling: false # Optional, if not provided, defaults to false
  on-tag: true # Optional, if not provided, defaults to true
