version: 1

build:
  type: golang
  dockerfile: Dockerfile  # Optional, if not provided, defaults to "Dockerfile"
  upload_artifacts: true

release:
  rolling: false # Optional, if not provided, defaults to false
  on-tag: true # Optional, if not provided, defaults to true
